name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - source
  schedule:
    - cron: '0 0 * * 0' # every Sunday at midnight

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write # required for peter-evans/create-issue-from-file
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: "--verbose ./src/content/blog/*.md ./src/content/newsletters/*.md ./src/content/initiatives/*.md"
          fail: false

      # - name: Create Issue From File
      #   if: steps.lychee.outputs.exit_code != 0
      #   uses: peter-evans/create-issue-from-file@v5
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: report, automated issue
